# config_DexNet.yaml

name: "FaithfulDexNet3"
model: "dexnet3"
optimizer:
  name: "SGD"
  learning_rate: 0.005
  momentum: .9
  scheduler_gamma: .90   #original: .95, but orig does every .66 epoch
  weight_decay: .0005
training:
  dataset_path: "dataset/dexnet_3/dexnet_09_13_17"
  batch_size: 256
  num_epochs: 25
  resize: false
  GT_threshold: 0.2
  wandb: true
  ordered_split: true
  pos_weigh: 4
outputs:
  save_directory: "outputs/DexNet3"
  save_name: "dex3_class_imbalance"
  training_print_every: 500
  val_print_every: 2000
  save_every_x_epoch: 10

  

